
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Choisissez une couleur pour votre client</title>
<meta http-equiv="Content-Type" content="text/html); charset=iso-8859-1">

<SCRIPT LANGUAGE="JavaScript">
NavName = navigator.appName;
NavVers = navigator.appVersion;
Navigateur = "name : "+NavName + " Version : " + NavVers;
if( NavName == "Microsoft Internet Explorer" )
	ie = true;
else
	ie = false;
</SCRIPT>


</head>
<body onBlur="javascript:if(!ie)self.close();">
<center>
Choisissez votre couleur
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
			<table cellspacing=0 cellpadding=0 border="0">
        <tr>
          <td width="10" height="10" bgcolor="#000000"><a href="#" onClick="opener.modif_couleur('000000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#000033"><a href="#" onClick="opener.modif_couleur('000033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#000066"><a href="#" onClick="opener.modif_couleur('000066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#000099"><a href="#" onClick="opener.modif_couleur('000099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0000CC"><a href="#" onClick="opener.modif_couleur('0000CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0000FF"><a href="#" onClick="opener.modif_couleur('0000FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#003300"><a href="#" onClick="opener.modif_couleur('003300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#003333"><a href="#" onClick="opener.modif_couleur('003333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#003366"><a href="#" onClick="opener.modif_couleur('003366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#003399"><a href="#" onClick="opener.modif_couleur('003399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0033CC"><a href="#" onClick="opener.modif_couleur('0033CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0033FF"><a href="#" onClick="opener.modif_couleur('0033FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#006600"><a href="#" onClick="opener.modif_couleur('006600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#006633"><a href="#" onClick="opener.modif_couleur('006633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#006666"><a href="#" onClick="opener.modif_couleur('006666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#006699"><a href="#" onClick="opener.modif_couleur('006699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0066CC"><a href="#" onClick="opener.modif_couleur('0066CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0066FF"><a href="#" onClick="opener.modif_couleur('0066FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#009900"><a href="#" onClick="opener.modif_couleur('009900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#009933"><a href="#" onClick="opener.modif_couleur('009933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#009966"><a href="#" onClick="opener.modif_couleur('009966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#009999"><a href="#" onClick="opener.modif_couleur('009999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0099CC"><a href="#" onClick="opener.modif_couleur('0099CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#0099FF"><a href="#" onClick="opener.modif_couleur('0099FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#00CC00"><a href="#" onClick="opener.modif_couleur('00CC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00CC33"><a href="#" onClick="opener.modif_couleur('00CC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00CC66"><a href="#" onClick="opener.modif_couleur('00CC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00CC99"><a href="#" onClick="opener.modif_couleur('00CC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00CCCC"><a href="#" onClick="opener.modif_couleur('00CCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00CCFF"><a href="#" onClick="opener.modif_couleur('00CCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#00FF00"><a href="#" onClick="opener.modif_couleur('00FF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00FF33"><a href="#" onClick="opener.modif_couleur('00FF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00FF66"><a href="#" onClick="opener.modif_couleur('00FF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00FF99"><a href="#" onClick="opener.modif_couleur('00FF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00FFCC"><a href="#" onClick="opener.modif_couleur('00FFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#00FFFF"><a href="#" onClick="opener.modif_couleur('00FFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
        </td>
    <td><table cellspacing=0 cellpadding=0  border="0">
        <tr>
          <td width="10" height="10" bgcolor="#330000"><a href="#" onClick="opener.modif_couleur('330000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#330033"><a href="#" onClick="opener.modif_couleur('330033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#330066"><a href="#" onClick="opener.modif_couleur('330066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#330099"><a href="#" onClick="opener.modif_couleur('330099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3300CC"><a href="#" onClick="opener.modif_couleur('3300CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3300FF"><a href="#" onClick="opener.modif_couleur('3300FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#333300"><a href="#" onClick="opener.modif_couleur('333300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#333333"><a href="#" onClick="opener.modif_couleur('333333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#333366"><a href="#" onClick="opener.modif_couleur('333366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#333399"><a href="#" onClick="opener.modif_couleur('333399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3333CC"><a href="#" onClick="opener.modif_couleur('3333CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3333FF"><a href="#" onClick="opener.modif_couleur('3333FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#336600"><a href="#" onClick="opener.modif_couleur('336600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#336633"><a href="#" onClick="opener.modif_couleur('336633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#336666"><a href="#" onClick="opener.modif_couleur('336666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#336699"><a href="#" onClick="opener.modif_couleur('336699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3366CC"><a href="#" onClick="opener.modif_couleur('3366CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3366FF"><a href="#" onClick="opener.modif_couleur('3366FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#339900"><a href="#" onClick="opener.modif_couleur('339900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#339933"><a href="#" onClick="opener.modif_couleur('339933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#339966"><a href="#" onClick="opener.modif_couleur('339966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#339999"><a href="#" onClick="opener.modif_couleur('339999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3399CC"><a href="#" onClick="opener.modif_couleur('3399CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#3399FF"><a href="#" onClick="opener.modif_couleur('3399FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#33CC00"><a href="#" onClick="opener.modif_couleur('33CC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33CC33"><a href="#" onClick="opener.modif_couleur('33CC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33CC66"><a href="#" onClick="opener.modif_couleur('33CC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33CC99"><a href="#" onClick="opener.modif_couleur('33CC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33CCCC"><a href="#" onClick="opener.modif_couleur('33CCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33CCFF"><a href="#" onClick="opener.modif_couleur('33CCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#33FF00"><a href="#" onClick="opener.modif_couleur('33FF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33FF33"><a href="#" onClick="opener.modif_couleur('33FF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33FF66"><a href="#" onClick="opener.modif_couleur('33FF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33FF99"><a href="#" onClick="opener.modif_couleur('33FF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33FFCC"><a href="#" onClick="opener.modif_couleur('33FFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#33FFFF"><a href="#" onClick="opener.modif_couleur('33FFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
        </td>
    <td><table cellspacing=0 cellpadding=0  border="0">
        <tr>
          <td width="10" height="10" bgcolor="#660000"><a href="#" onClick="opener.modif_couleur('660000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#660033"><a href="#" onClick="opener.modif_couleur('660033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#660066"><a href="#" onClick="opener.modif_couleur('660066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#660099"><a href="#" onClick="opener.modif_couleur('660099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6600CC"><a href="#" onClick="opener.modif_couleur('6600CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6600FF"><a href="#" onClick="opener.modif_couleur('6600FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#663300"><a href="#" onClick="opener.modif_couleur('663300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#663333"><a href="#" onClick="opener.modif_couleur('663333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#663366"><a href="#" onClick="opener.modif_couleur('663366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#663399"><a href="#" onClick="opener.modif_couleur('663399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6633CC"><a href="#" onClick="opener.modif_couleur('6633CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6633FF"><a href="#" onClick="opener.modif_couleur('6633FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#666600"><a href="#" onClick="opener.modif_couleur('666600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#666633"><a href="#" onClick="opener.modif_couleur('666633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#666666"><a href="#" onClick="opener.modif_couleur('666666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#666699"><a href="#" onClick="opener.modif_couleur('666699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6666CC"><a href="#" onClick="opener.modif_couleur('6666CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6666FF"><a href="#" onClick="opener.modif_couleur('6666FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#669900"><a href="#" onClick="opener.modif_couleur('669900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#669933"><a href="#" onClick="opener.modif_couleur('669933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#669966"><a href="#" onClick="opener.modif_couleur('669966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#669999"><a href="#" onClick="opener.modif_couleur('669999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6699CC"><a href="#" onClick="opener.modif_couleur('6699CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#6699FF"><a href="#" onClick="opener.modif_couleur('6699FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#66CC00"><a href="#" onClick="opener.modif_couleur('66CC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66CC33"><a href="#" onClick="opener.modif_couleur('66CC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66CC66"><a href="#" onClick="opener.modif_couleur('66CC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66CC99"><a href="#" onClick="opener.modif_couleur('66CC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66CCCC"><a href="#" onClick="opener.modif_couleur('66CCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66CCFF"><a href="#" onClick="opener.modif_couleur('66CCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#66FF00"><a href="#" onClick="opener.modif_couleur('66FF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66FF33"><a href="#" onClick="opener.modif_couleur('66FF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66FF66"><a href="#" onClick="opener.modif_couleur('66FF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66FF99"><a href="#" onClick="opener.modif_couleur('66FF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66FFCC"><a href="#" onClick="opener.modif_couleur('66FFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#66FFFF"><a href="#" onClick="opener.modif_couleur('66FFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
        </td>
  </tr>
  <tr>
    <td><table cellspacing=0 cellpadding=0 border="0">
        <tr>
          <td width="10" height="10" bgcolor="#990000"><a href="#" onClick="opener.modif_couleur('990000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#990033"><a href="#" onClick="opener.modif_couleur('990033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#990066"><a href="#" onClick="opener.modif_couleur('990066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#990099"><a href="#" onClick="opener.modif_couleur('990099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9900CC"><a href="#" onClick="opener.modif_couleur('9900CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9900FF"><a href="#" onClick="opener.modif_couleur('9900FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#993300"><a href="#" onClick="opener.modif_couleur('993300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#993333"><a href="#" onClick="opener.modif_couleur('993333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#993366"><a href="#" onClick="opener.modif_couleur('993366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#993399"><a href="#" onClick="opener.modif_couleur('993399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9933CC"><a href="#" onClick="opener.modif_couleur('9933CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9933FF"><a href="#" onClick="opener.modif_couleur('9933FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#996600"><a href="#" onClick="opener.modif_couleur('996600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#996633"><a href="#" onClick="opener.modif_couleur('996633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#996666"><a href="#" onClick="opener.modif_couleur('996666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#996699"><a href="#" onClick="opener.modif_couleur('996699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9966CC"><a href="#" onClick="opener.modif_couleur('9966CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9966FF"><a href="#" onClick="opener.modif_couleur('9966FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#999900"><a href="#" onClick="opener.modif_couleur('999900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#999933"><a href="#" onClick="opener.modif_couleur('999933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#999966"><a href="#" onClick="opener.modif_couleur('999966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#999999"><a href="#" onClick="opener.modif_couleur('999999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9999CC"><a href="#" onClick="opener.modif_couleur('9999CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#9999FF"><a href="#" onClick="opener.modif_couleur('9999FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#99CC00"><a href="#" onClick="opener.modif_couleur('99CC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99CC33"><a href="#" onClick="opener.modif_couleur('99CC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99CC66"><a href="#" onClick="opener.modif_couleur('99CC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99CC99"><a href="#" onClick="opener.modif_couleur('99CC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99CCCC"><a href="#" onClick="opener.modif_couleur('99CCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99CCFF"><a href="#" onClick="opener.modif_couleur('99CCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#99FF00"><a href="#" onClick="opener.modif_couleur('99FF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99FF33"><a href="#" onClick="opener.modif_couleur('99FF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99FF66"><a href="#" onClick="opener.modif_couleur('99FF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99FF99"><a href="#" onClick="opener.modif_couleur('99FF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99FFCC"><a href="#" onClick="opener.modif_couleur('99FFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#99FFFF"><a href="#" onClick="opener.modif_couleur('99FFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
        </td>
    <td><table cellspacing=0 cellpadding=0  border="0">
        <tr>
          <td width="10" height="10" bgcolor="#CC0000"><a href="#" onClick="opener.modif_couleur('CC0000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC0033"><a href="#" onClick="opener.modif_couleur('CC0033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC0066"><a href="#" onClick="opener.modif_couleur('CC0066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC0099"><a href="#" onClick="opener.modif_couleur('CC0099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC00CC"><a href="#" onClick="opener.modif_couleur('CC00CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC00FF"><a href="#" onClick="opener.modif_couleur('CC00FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#CC3300"><a href="#" onClick="opener.modif_couleur('CC3300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC3333"><a href="#" onClick="opener.modif_couleur('CC3333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC3366"><a href="#" onClick="opener.modif_couleur('CC3366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC3399"><a href="#" onClick="opener.modif_couleur('CC3399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC33CC"><a href="#" onClick="opener.modif_couleur('CC33CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC33FF"><a href="#" onClick="opener.modif_couleur('CC33FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#CC6600"><a href="#" onClick="opener.modif_couleur('CC6600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC6633"><a href="#" onClick="opener.modif_couleur('CC6633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC6666"><a href="#" onClick="opener.modif_couleur('CC6666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC6699"><a href="#" onClick="opener.modif_couleur('CC6699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC66CC"><a href="#" onClick="opener.modif_couleur('CC66CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC66FF"><a href="#" onClick="opener.modif_couleur('CC66FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#CC9900"><a href="#" onClick="opener.modif_couleur('CC9900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC9933"><a href="#" onClick="opener.modif_couleur('CC9933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC9966"><a href="#" onClick="opener.modif_couleur('CC9966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC9999"><a href="#" onClick="opener.modif_couleur('CC9999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC99CC"><a href="#" onClick="opener.modif_couleur('CC99CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CC99FF"><a href="#" onClick="opener.modif_couleur('CC99FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#CCCC00"><a href="#" onClick="opener.modif_couleur('CCCC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCCC33"><a href="#" onClick="opener.modif_couleur('CCCC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCCC66"><a href="#" onClick="opener.modif_couleur('CCCC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCCC99"><a href="#" onClick="opener.modif_couleur('CCCC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCCCCC"><a href="#" onClick="opener.modif_couleur('CCCCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCCCFF"><a href="#" onClick="opener.modif_couleur('CCCCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#CCFF00"><a href="#" onClick="opener.modif_couleur('CCFF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCFF33"><a href="#" onClick="opener.modif_couleur('CCFF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCFF66"><a href="#" onClick="opener.modif_couleur('CCFF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCFF99"><a href="#" onClick="opener.modif_couleur('CCFF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCFFCC"><a href="#" onClick="opener.modif_couleur('CCFFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#CCFFFF"><a href="#" onClick="opener.modif_couleur('CCFFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
        </td>
    <td><table cellspacing=0 cellpadding=0  border="0">
        <tr>
          <td width="10" height="10" bgcolor="#FF0000"><a href="#" onClick="opener.modif_couleur('FF0000');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF0033"><a href="#" onClick="opener.modif_couleur('FF0033');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF0066"><a href="#" onClick="opener.modif_couleur('FF0066');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF0099"><a href="#" onClick="opener.modif_couleur('FF0099');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF00CC"><a href="#" onClick="opener.modif_couleur('FF00CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF00FF"><a href="#" onClick="opener.modif_couleur('FF00FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#FF3300"><a href="#" onClick="opener.modif_couleur('FF3300');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF3333"><a href="#" onClick="opener.modif_couleur('FF3333');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF3366"><a href="#" onClick="opener.modif_couleur('FF3366');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF3399"><a href="#" onClick="opener.modif_couleur('FF3399');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF33CC"><a href="#" onClick="opener.modif_couleur('FF33CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF33FF"><a href="#" onClick="opener.modif_couleur('FF33FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#FF6600"><a href="#" onClick="opener.modif_couleur('FF6600');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF6633"><a href="#" onClick="opener.modif_couleur('FF6633');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF6666"><a href="#" onClick="opener.modif_couleur('FF6666');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF6699"><a href="#" onClick="opener.modif_couleur('FF6699');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF66CC"><a href="#" onClick="opener.modif_couleur('FF66CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF66FF"><a href="#" onClick="opener.modif_couleur('FF66FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#FF9900"><a href="#" onClick="opener.modif_couleur('FF9900');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF9933"><a href="#" onClick="opener.modif_couleur('FF9933');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF9966"><a href="#" onClick="opener.modif_couleur('FF9966');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF9999"><a href="#" onClick="opener.modif_couleur('FF9999');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF99CC"><a href="#" onClick="opener.modif_couleur('FF99CC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FF99FF"><a href="#" onClick="opener.modif_couleur('FF99FF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#FFCC00"><a href="#" onClick="opener.modif_couleur('FFCC00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFCC33"><a href="#" onClick="opener.modif_couleur('FFCC33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFCC66"><a href="#" onClick="opener.modif_couleur('FFCC66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFCC99"><a href="#" onClick="opener.modif_couleur('FFCC99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFCCCC"><a href="#" onClick="opener.modif_couleur('FFCCCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFCCFF"><a href="#" onClick="opener.modif_couleur('FFCCFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
        <tr>
          <td width="10" height="10" bgcolor="#FFFF00"><a href="#" onClick="opener.modif_couleur('FFFF00');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFFF33"><a href="#" onClick="opener.modif_couleur('FFFF33');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFFF66"><a href="#" onClick="opener.modif_couleur('FFFF66');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFFF99"><a href="#" onClick="opener.modif_couleur('FFFF99');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFFFCC"><a href="#" onClick="opener.modif_couleur('FFFFCC');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
          <td width="10" height="10" bgcolor="#FFFFFF"><a href="#" onClick="opener.modif_couleur('FFFFFF');return false"><img src="dummy.gif" alt="couleur" width="10" height="10" border="0"></a></td>
        </tr>
      </table>
		</td>
</table>
	<table cellspacing=0 cellpadding=0 border=0>
		<tr>
			<td bgcolor="#FFFFFF" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('FFFFFF');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#DDDDDD" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('DDDDDD');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#C0C0C0" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('C0C0C0');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#969696" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('969696');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#808080" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('808080');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#646464" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('646464');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#4B4B4B" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('4B4B4B');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#242424" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('242424');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
			<td bgcolor="#000000" width=10 height=10 ><a href="#" onClick="opener.modif_couleur('000000');return false"><img src="/images/dummy.gif" width="10" height="10" border="0"></a></td>
		</tr>
	</table>
<a href="javascript:self.close()">Fermer</a> 
</center>
</body>
</html>
